services:
    db:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        #command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: gestor
            MYSQL_USER: admin
            MYSQL_PASSWORD: abc123.
            MYSQL_ROOT_PASSWORD: abc123.
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            timeout: 5s
            retries: 5
    www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html
        links:
            - db
        networks:
            - default
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            db:
                condition: service_healthy
    phpmyadmin:
        image: phpmyadmin:5.2.1
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
volumes:
    persistent:
